module.exports = {
  apps: [
    {
      name: 'omniplan-server',
      cwd: './packages/server',
      script: 'npx',
      args: 'tsx src/index.ts',
      interpreter: 'none',
      env: {
        PORT: '3001',
        NODE_ENV: 'production',
      },
      autorestart: true,
      max_restarts: 10,
      restart_delay: 1000,
      max_memory_restart: '512M',
      error_file: '/tmp/omniplan-server-error.log',
      out_file: '/tmp/omniplan-server-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      kill_timeout: 5000,
      wait_ready: false,
      listen_timeout: 10000,
    },
    {
      name: 'omniplan-web',
      cwd: './packages/web',
      script: 'npx',
      args: 'vite --host 0.0.0.0 --port 1101',
      interpreter: 'none',
      env: {
        VITE_SERVER_URL: 'http://localhost:3001',
      },
      autorestart: true,
      max_restarts: 10,
      restart_delay: 1000,
      max_memory_restart: '512M',
      error_file: '/tmp/omniplan-web-error.log',
      out_file: '/tmp/omniplan-web-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      kill_timeout: 5000,
      listen_timeout: 10000,
    },
  ],
};
